elastic/ems-file-service

build.sh, deployProduction.sh, deployStaging.sh
GCP bucket names are:
```
${GPROJECT}-files-vector << production
${GPROJECT}-files-vector-staging << staging
${GPROJECT}-archive << archive
```
=> Fix bucket names

README.md, templates/source_template.hjson
This PR includes instructions for adding a new subdivision layer to ems-file-service. Please let me know if anything is unclear.
Fixes #4
=> Instructions for adding new vector layer

scripts/generate-manifest.js, test/fixtures/invalid-sources/bad-versions.json, test/manifest-v2.js
=> Catch bad versions in sources

scripts/constants.js, scripts/generate-manifest.js
The new manifest changes have been bumped to 7.2 iso 7.1. So the next EMS version release should be 7.2.
=> Bump new manifest release to v7.2

.ci/jobs/defaults.yml, .ci/jobs/elastic+ems-file-service+deploy.yml, .ci/jobs/elastic+ems-file-service+master+stage.yml, build.sh, deployProduction.sh, deployStaging.sh
Use a different GCP project & buckets
=> Switch to Bekitzur project for hosting

README.md
This updates the instructions for creating new vector layers using the feature-layers branch.
=> Update README for feature-layers branch

scripts/constants.js
This PR will publish vector files for EMS v7.8.
cc @aaronjcaldwell @thomasneirynck
=> Publish EMS v7.8

.ci/jobs/defaults.yml, .ci/jobs/elastic+ems-file-service+deploy.yml, .ci/jobs/elastic+ems-file-service+feature-layers.yml, .ci/jobs/elastic+ems-file-service+master+stage.yml
Switch the role for deployment
=> [bekitzur] use specific role for deployment

scripts/constants.js
=> Publish v7.9 endpoint

scripts/constants.js
=> Create EMS v7.10 endpoint

scripts/constants.js
=> Create EMS v7.11 endpoint

scripts/constants.js, test/manifest-v7.14.js
Adds the generation of a 7.17 manifest file
=> Add 7.17 release

schema/source_schema.json, scripts/generate-manifest.js, sources/cl/chile-regions-v1.hjson, sources/cl/chile-regions-v82.hjson, sources/cn/provinces-v1.hjson, sources/cn/provinces-v82.hjson, sources/fr/departments_v82.hjson, sources/ie/ireland-counties-v1.hjson, sources/ie/ireland-counties-v82.hjson, sources/it/provinces_v82.hjson, sources/it/regions-v1.hjson, sources/it/regions-v82.hjson, sources/jp/prefectures-v1.hjson, sources/jp/prefectures-v82.hjson, sources/us/counties-v2.hjson, sources/us/counties-v82.hjson, sources/us/zip_codes_v82.hjson, sources/world/world_countries_v82.hjson, test/fixtures/valid-sources/sources.json, test/manifest-v7.14.js
Fixes #242
- Add a new `skipCopy` property for the `fieldMapping` that avoids copying actual field values into the manifest
- Add the new property to fields that are just numbers
To test this PR you can build the manifests and run `jq` on the world countries to check for fields of `type: id` and the existence of a `values` key.
For 8.1 it presents `iso_numeric`:
```
$ cat dist/vector/v8.1/manifest |\
jq -c '.layers[] | 
select (.layer_id == "world_countries") | 
.fields[] |
select(.type =="id" and .values != null) |
{ id : .id }'
{"id":"iso2"}
{"id":"iso3"}
{"id":"iso_numeric"}
```
And for `8.2` it does not present `iso_numeric`:
```
$ cat dist/vector/v8.2/manifest |\
jq -c '.layers[] | 
select (.layer_id == "world_countries") | 
.fields[] |
select(.type =="id" and .values != null) |
{ id …
```
=> Avoid adding common values on identifier fields

sources/ma/regions_v1.hjson
Fixes #259
Small fixes to human readable labels in different langagues to uppercase the initial and change the English lable to follow the same pattern as all the other layers with the name of the region first.
cc. @nelmalki
=> Fix Morocco regions human readable labels

yarn.lock
Upgrading from `yarn upgrade-interactive`
=> Upgrade semver and node-fetch

scripts/constants.js
Instructs the build script to generate manifests up to `8.14`
=> Adds manifests up to 8.14

.buildkite/deploy.sh
=> Set metadata for the vector index document

README.md
Just adding some details to the `README` about how we manage date-based versions, to give more details to #287.
=> Update README with versioning details

.buildkite/pipeline.yml, renovate.json
- [add retry to test step (#333)](https://github.com/elastic/ems-file-service/pull/333)
=> [feature-layers] add retry to test step (#333)

.buildkite/pipeline.yml, .nvmrc
Update CI pipeline and references for Node 22.
=> Update to Node 22
