build.sh, deployProduction.sh, deployStaging.sh, index.js, scripts/constants.js, scripts/generate-manifest.js, test/generate-manifest.js
This adds code to generate and deploy the catalogue manifest.
Adding the catalogue manifest to the deployment scripts might not be necessary at this time since it's a very static file. I'm on the fence about that. Would appreciate input from the team.
=> Generate catalogue manifest

scripts/generate-manifest.js, test/fixtures/sources.json, test/generate-manifest.js, test/generate-vectors.js
To resolve issues with older versions of Kibana (e.g. 5.x), we should continue to maintain the `blob/{id}` URL path for layers in the current manifests. After the migration period is over, new layer sources can be added without an `id` field. In that case, the new layer will appear in the manifest as `files/{filename}`. 
When we release a new major version of EMS `>v2`, we can create manifests using the `files/{filename}` URL path in the manifest.
=> Use URL `{hostname}/blob/{id}` when `id` exists otherwise `{hostname}/files/{filename}`

sources/au/states.hjson, sources/ca/provinces.hjson, sources/ch/switzerland-cantons.hjson, sources/de/states.hjson, sources/fr/departments.hjson, sources/ie/ireland-counties.hjson, sources/jp/prefectures.hjson, sources/us/counties.hjson, sources/us/states.hjson, sources/zh/provinces.hjson
The OpenStreetMap attribution link should match how it's done in the tiles manifest to avoid duplicate attributions in Kibana region maps. The duplicate EMS attributions should be fixed by resolving the issue in https://github.com/elastic/kibana/pull/22003#issuecomment-414770867.
=> [chore] Fix OpenStreetMap attribution link

build.sh
If we continue to use `cp` to copy files, we run the risk of leaving old, unused files on the bucket. Using `rsync` with the `-d` flag will copy files from the locally generated directories (`dist/`) and remove files from the bucket that don't exist in `dist`. 
This may appear dangerous, but we create archives of our production deployments on a separate bucket so we can always restore data from the archive if something goes wrong.
=> Use rsync instead of cp for deploying to buckets

build.sh
`gsutil rsync` does not have an equivalent to the `cp -Z` flag to gzip files stored on the bucket. The `rsync -J` flag only appears to compress files during upload and leaves uncompressed files on the server.
My preference is to keep using `gsutil cp` and manually delete files in the bucket if necessary. 
In the future we may choose to create gzipped files in the `dist` directory using JavaScript. Then we can use `rsync`.
=> Revert to using `cp` to copy files

test/generate-manifest.js
The `https://staging-dot-elastic-layer.appspot.com` URL shown in these tests has been deprecated and is no longer used.  These tests do not make actual requests to the URL, but the URLs should be updated to avoid confusion.
=> Remove deprecated URL from tests

scripts/generate-manifest.js, test/manifest-v6.js
Fixes #61.
All layers in the v1 and v2 manifests can be uniquely referenced in Kibana saved objects using the `name` field. This PR will allow us to map the `name` field in the saved object to the appropriate layer via `legacy_ids` in the v6.6 manifest. 
Since all saved objects include the `name` field there is no need to add any additional strings to the `legacy_ids` array at this time. However, we want to retain the ability to add additional strings to the `legacy_ids` array as needed in the future.
=> Add legacy_ids array to v6.6 manifest

index.js
Fixes #50.
Vector files stored in [`data/`]() may include whitespace and line breaks for human-readability and better diffing. 
We want to ensure that any unnecessary whitespace and line breaks are removed from vector files published to production to decrease file size and improve performance for the end-user. 
There is no rush on this and we can merge after v6.6 is published.
=> Minify vector files copied to dist/

sources/us/README.md, sources/us/counties.hjson
The current precedent for human readable layer names in English is plural. We should continue this precedent.
=> Match plural convention for `en` names for USA Counties

sources/fr/departments_v1.hjson
Semver ranges with a hyphen and inclusive and do not accept operators such as < and >.
=> Fix semver range for France

scripts/constants.js, scripts/generate-manifest.js
Publish a new catalogue manifest with support for [v7.1 tiles manifest](https://tiles.maps.elastic.co/v7.1/manifest).
=> Publish 7.1 manifest

build.sh, deployStaging.sh, scripts/constants.js, test/manifest-v1.js, test/manifest-v2.js, test/manifest-v6.js
Under the new tile server architecture, the staging URLs for the tiles need to be updated. This does not affect production users in any way.
=> Update staging URL for tiles manifest

.ci/jobs/elastic+ems-file-service+feature-layers.yml, deployDev.sh, deployProduction.sh, deployStaging.sh
To make new layer development easier to test, I propose developing new layers on the `feature-layers` branch. Any new layers being developed will be committed to this branch. This will build catalogue and vector manifests on a development storage bucket that are suitable for testing with Kibana by modifying the `map.manifestServiceUrl` parameter in `kibana.yml`. 
When ready to be reviewed and published, a pull request from the `feature-layers` branch will be opened against `master`. 
Code changes and pull requests not related to new layer development should continue to be created on new branches from `master`. The `feature-layers` branch would only be used for new vector layer development.
https://github.com/elastic/infra/issues/9313
=> Add ci job for feature-layers branch

README.md, sources/ar/argentina-provinces.hjson, sources/bo/bolivia-departments.hjson, sources/cl/chile-regions.hjson, sources/co/colombia-departments.hjson, sources/ec/ecuador-provinces.hjson, sources/gy/guyana-regions.hjson, sources/pe/peru-regions.hjson, sources/py/paraguay-departments.hjson, sources/sr/suriname-districts.hjson, sources/uy/uruguay-departments.hjson, sources/ve/venezuela-states.hjson
We should match the current precedent of capitalizing the
first letter of the country and subdivision type in the layer label.
=> Capitalize subdivision type in layer labels

data/france_departments_v7.geo.json
Fixes #119 
There was a typo in the [Wikidata entry](https://www.wikidata.org/wiki/Q46130) which caused this error. [Wikidata has since been corrected](https://www.wikidata.org/w/index.php?title=Q46130&diff=941373819&oldid=941373589) and I have confirmed this is correct with the official source at https://www.insee.fr/fr/information/2114819#titre-bloc-26. 
This only affects EMS and Kibana versions 7+. Previous versions of EMS and Kibana were not impacted.
=> Fix INSEE code for Rhône department of FR

docs/wikidata-quickstatements.md
@jsanz I'm considering adding this example process for quickly adding missing OSM relations to Wikidata entities. I think this process may be useful for other countries. Let me know if anything is unclear.
You can try this yourself with Serbia districts. Change `ME-` to `RS-` in the Sophox query.
=> [skip-ci] Document quickstatement example

index.js, scripts/constants.js, scripts/generate-manifest.js, test/manifest-v7.js
Fixes #138 
To test this, run `yarn build` and check that the catalogue manifest **does not** get created in the ./dist/v7.6 subdirectory. Also check that the catalogue manifest **does** get created in prior releases (e.g. v2, v6.x, v7.0, v7.2).
=> EMS v7.6 - remove catalogue manifest

package-lock.json, package.json, scripts/clean-geom.js
Mostly motivated by the issue we found for France departments related to the script generating `null` geometries, I've improved the script to add minimal reporting capabilities.
I included `yargs` to declare two options for the script to enable logging and also to save the output in an alternate path. The default behavior is exactly the same it had. The library also enables a `--help` flag to automatically describe the options.
```text
$ node scripts/clean-geom.js --help
Options:
--help         Show help                                             [boolean]
--version      Show version number                                   [boolean]
--verbose, -v  Log about the process                [boolean] [default: false]
--output, -o   Write the output GeoJSON in a different path …
```
=> Improving the cleaning  script

build.sh
Support for Node.js v8 will reach end of life on 2019-12-31. I propose we use the LTS release for the Node.js docker images going forward.
Alternatively, we could try to keep the Node.js version in sync with Kibana (currently `10`). But I do not see the need and `node:lts` (currently `12`) is perpetually updated.
=> Use Node.js LTS docker image for building

scripts/generate-manifest.js, test/manifest-bad.js, test/manifest-v1.js, test/manifest-v2.js, test/manifest-v6.js, test/manifest-v7.2.js, test/manifest-v7.6.js
Partially fixes #159 
This PR adds a root level `version` property to all catalogue and vector file manifests containing the EMS version in the form of "{major}.{minor}" (e.g. 1.0, 2.0, 6.6, 7.2). 
Since this only adds a new property and does not modify the schema of the manifests otherwise, I believe this is safe to apply retroactively to all EMS versions. I have successfully tested these manifests in Kibana 5.6.14, 6.8.0, 7.1.1, 7.2.1, and the 7.6 branch.
=> Add EMS version to manifests

scripts/constants.js
As of 7.6, EMS is matching the latest minor stack release. So we should prepare v7.7 ahead of release.
There are no significant changes from the v7.6 release.
=> Prepare EMS v7.7

package.json, yarn.lock
This is required because the jsts dependency dropped support for Node <12.
Also fixes yarn.lock.
=> Drop support for Node < 12

data/italy_provinces_v1.geo.json
Fixes #189 
South Sardinia ISO code was added to the revision of Italy provinces ([provinces_v2.htjson](https://github.com/elastic/ems-file-service/blob/master/sources/it/provinces_v2.hjson)) that will be available in the next major, but never _backported_ to the older version.
This is just a replacement of the ISO code, without running the full Sophox procedure.
=> Add IT-SD code to Italy Provinces dataset

scripts/constants.js
Part of #202 
This will publish the v7.12 endpoint at https://vector-staging.maps.elastic.co/v7.12/manifest. https://vector.maps.elastic.co/v7.12/manifest will be published at a later date.
=> Add v7.12 endpoint

scripts/constants.js
Part of #206.
This PR will set up the Elastic Maps Service release for 7.13. 
Note: This also adds releases up to 7.16 with the caveat that future releases of Elastic Maps Service are in development and may change at any time.
=> Release EMS 7.13

build.sh
Change the `lts` Docker image by the `fermium` (14.x) image series. We need to update our testing code to keep up with NodeJS.
=> Pin the build to Node Fermium releases

.nvmrc, build.sh, package.json, test/manifest-bad.js, test/manifest-v1.js, test/manifest-v2.js, test/manifest-v6.js, test/manifest-v7.14.js, test/manifest-v7.2.js, test/manifest-v7.6.js, test/vectors-all.js, yarn.lock
* Upgrading `tap` to `15.1.5`
* Following deprecation notices, witching `deepEquals` and `false` methods to the new `same` and `notOk`
* Making explicit the support for node versions between `12` and `16` in package.json `engines` section
* Adding a `.nvmrc` control file to allow automatic switch to node `16` (Gallium)
* Updating the build script to use the Docker `node:gallium` image
=> Upgrade to tap 15 and Node 16

index.js, package.json, scripts/constants.js, test/source.js, yarn.lock
Related to #231
This PR adds a new constant `GEOJSON_RFC7946`, set to `undefined` at this moment to not change the current results of tests and build, leaving the definition of this behavior for a follow-up PR when discussion in #231 is concluded.
When set to `true` to enforce the [RFC7946 standard](https://datatracker.ietf.org/doc/html/rfc7946#appendix-B.1) for polygon orientation in GeoJSON files, the build process will ensure that all published polygons in all data layers are counter-clockwise oriented. When testing with `EMS_STRICT_TEST` env var defined, it will report which data layers are not following the standard.
When set to `false` it will build all polygons clockwise oriented and with `EMS_STRICT_TEST` it will report the data layers that follow the RFC7946 standard and are …
=> Adds a constant to check GeoJSON RFC7946 testing and building

.nvmrc, build.sh, package.json
Fixes #264
Updates nvm configuration, build script, and `package.json` supported node engines to upgrade to build EMS file service assets with Node 18.
=> Upgrade to Node 18

build.sh, package.json, yarn.lock
* Just a few upgrades run through `yarn upgrade-interactive`.
* Removes the `spin` config setting from `build.sh`
* Adds a `--no-timeout` option to `tap` to prevent tests to fail
=> Upgrade ajv, node-fetch, tap, eslint-plugin, and fix build

index.js, scripts/constants.js, scripts/date-versions.js, scripts/generate-manifest.js, scripts/generate-vectors.js, test/manifest-date.js, test/manifest-v7.14.js
Resolves #286
This PR introduces support to define release versions tagged as ISO8601 (yyyy-mm-yy). A new array called `DATE_VERSIONS` in the `constants.js` file contains objects as in the block below. This definition provides the minimum changes to how manifests are generated, matching a date release with a Semantic release. Finally, a "latest" folder is also generated with the last entry on the `DATE_VERSIONS` array.
```
...
DATE_VERSIONS: [
{
date: "2023-10-31",
semver: "v8.10",
},
],
LATEST_TAG: "latest",
...
```
=> Support date versions

yarn.lock
```
info Direct dependencies
├─ eslint-plugin-import@2.28.1
├─ geolib@3.3.4
├─ node-fetch@2.7.0
└─ tap@16.3.9
```
=> Update yarn.lock via upgrade-interactive

.buildkite/deploy.sh, templates/index.html.tpl
Fixes #276
Fixes #290
Using `sed` and a template to print in `dist/vector/index.html` a minimal doc with the commit identifier of the built distribution.
=> Print a simple file with commit hash in the vector distribution root

sources/us/zip_codes_v82.hjson, sources/us/zip_codes_v8_13.hjson
fixes #300
This PR introduces a new version for USA zip codes addressing an error in a self-intersecting geometry for the zip code `87513`.
* A new source is added to leverage this change from 8.13
* A new GeoJSON with the fixed geometries is introduced
* The new source points to the same TopoJSON as the previous version, so this change does not impact Kibana Maps users.
=> Add a new version of USA Zip Codes fixing an invalid geometry at zip code 85713

.buildkite/pipeline.yml, package.json, yarn.lock
* Upgrade to `0.4` version of the CI agent
* Dependencies updated: tap, eslint, ajv, glob
=> [CI] Upgrade to the latest CI image and dependencies

.buildkite/pipeline.yml, package.json, yarn.lock
- [[CI] Upgrade to the latest CI image and upgrade tap, eslint, ajv, glob (#313)](https://github.com/elastic/ems-file-service/pull/313)
=> [feature-layers] [CI] Upgrade to the latest CI image and upgrade tap, eslint, ajv, glob (#313)

yarn.lock
- [Bump braces from 3.0.2 to 3.0.3 (#315)](https://github.com/elastic/ems-file-service/pull/315)
=> [feature-layers] Bump braces from 3.0.2 to 3.0.3 (#315)

yarn.lock
- [Bump ws from 8.17.0 to 8.17.1 (#317)](https://github.com/elastic/ems-file-service/pull/317)
=> [feature-layers] Bump ws from 8.17.0 to 8.17.1 (#317)

.buildkite/pipeline.yml
- [Update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 Docker tag to v0.5 (#336)](https://github.com/elastic/ems-file-service/pull/336)
=> [feature-layers] Update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 Docker tag to v0.5 (#336)

package.json, yarn.lock
- [Update dependency eslint to v9.9.1 (#335)](https://github.com/elastic/ems-file-service/pull/335)
=> [feature-layers] Update dependency eslint to v9.9.1 (#335)

package.json, yarn.lock
- [Update dependency eslint-plugin-import to v2.30.0 (#339)](https://github.com/elastic/ems-file-service/pull/339)
=> [feature-layers] Update dependency eslint-plugin-import to v2.30.0 (#339)

scripts/constants.js, scripts/generate-manifest.js
Similar to #229 for 8.x, setting up in advance our manifests for the first 9.x releases
=> Add support for first 9.x releases

scripts/constants.js, scripts/generate-manifest.js
- [Add support for first 9.x releases (#341)](https://github.com/elastic/ems-file-service/pull/341)
=> [feature-layers] Add support for first 9.x releases (#341)

package.json, yarn.lock
- [Update dependency eslint to v9.10.0 (#343)](https://github.com/elastic/ems-file-service/pull/343)
=> [feature-layers] Update dependency eslint to v9.10.0 (#343)

package.json, yarn.lock
- [Update dependency eslint to v9.11.1 (#347)](https://github.com/elastic/ems-file-service/pull/347)
=> [feature-layers] Update dependency eslint to v9.11.1 (#347)

package.json, yarn.lock
- [Update dependency @babel/eslint-parser to v7.25.7 (#349)](https://github.com/elastic/ems-file-service/pull/349)
=> [feature-layers] Update dependency @babel/eslint-parser to v7.25.7 (#349)

package.json, yarn.lock
- [Update dependency eslint to v9.12.0 (#352)](https://github.com/elastic/ems-file-service/pull/352)
=> [feature-layers] Update dependency eslint to v9.12.0 (#352)

package.json, yarn.lock
- [Update dependency eslint-plugin-import to v2.31.0 (#351)](https://github.com/elastic/ems-file-service/pull/351)
=> [feature-layers] Update dependency eslint-plugin-import to v2.31.0 (#351)

package.json, yarn.lock
- [Update dependency @babel/eslint-parser to v7.25.8 (#355)](https://github.com/elastic/ems-file-service/pull/355)
=> [feature-layers] Update dependency @babel/eslint-parser to v7.25.8 (#355)

package.json, yarn.lock
- [Update dependency eslint to v9.13.0 (#357)](https://github.com/elastic/ems-file-service/pull/357)
=> [feature-layers] Update dependency eslint to v9.13.0 (#357)

package.json, yarn.lock
- [Update dependency @babel/eslint-parser to v7.25.9 (#359)](https://github.com/elastic/ems-file-service/pull/359)
=> [feature-layers] Update dependency @babel/eslint-parser to v7.25.9 (#359)

sources/us/states_v1.hjson, sources/us/states_v8.hjson
Related to https://github.com/elastic/ems-file-service/pull/230
Since we never developed a migration in Kibana to address changes in #152, pushing the same changes done #230 for the 9 series so this layer is published on this major version.
=> [data] Publish USA States for 9

package.json, yarn.lock
- [Update dependency eslint to v9.32.0 (#468)](https://github.com/elastic/ems-file-service/pull/468)
=> [feature-layers] Update dependency eslint to v9.32.0 (#468)
